#!/usr/bin/env tclsh

# Shell colors
set norm  "\033\[0m"
set grey  "\033\[38;5;238m"
set white "\033\[38;5;255m"
set pink  "\033\[38;5;162m"
set bold  "\033\[1m"

# Get the currently logged-in user
set pid     [pid]
set ppid    [lindex [exec -- ps -o pid,ppid $pid] 3]
set ppid1   [lindex [exec -- cat "/proc/$ppid/status" | grep PPid] 1]
set ppid2   [lindex [exec -- cat "/proc/$ppid1/status" | grep PPid] 1]
set process [exec -- ps -x | grep $ppid2]
set user    [lindex "$process" 5]


# Get the FQDN for this server
set host [exec -- hostname]
set fqdn [exec -- hostname -f]
set fqdn [exec -- sed -e "s/\[.]/$grey.$pink/g" << "$fqdn"]

# Get the client IP address
#set ssh(base)   $env(SSH_CONNECTION)
#set ssh(cip)    [lindex $ssh(base) 0]
#set ssh(cip)    [exec -- sed -e "s/\[.]/$grey.$pink/g" << "$ssh(cip)"]
#set ssh(cport)  [lindex $ssh(base) 1]
#set ssh(sport)  [lindex $ssh(base) 2]

# Get the current date
set date(base)  [exec -- date]
set date(day)   [lindex "$date(base)" 0]
set date(month) [lindex "$date(base)" 1]
set date(date)  [lindex "$date(base)" 2]
set date(time)  [lindex "$date(base)" 3]
set date(year)  [lindex "$date(base)" 5]

# Draw the box
set tl [string length "$user @ $host"]
set tb [string repeat "═" [expr "$tl + 2"]]
set hb [string repeat "═" [expr "(78 - $tl - 5) / 2"]]
set hv [string repeat " " [expr "(78 - $tl - 5) / 2"]]

set title "$pink$user$norm @ $pink$host$grey"
if [expr "$tl % 2" > 0 ] {
  set title "$pink$user$norm $norm$host"
}

set l(1) [format "%-89s" "Hello $pink$user$norm,"]
set l(2) [format "%-133s" "Welcome on the server $pink$fqdn$norm."]
#set l(3) [format "%-155s" "Your current IP address is $pink$ssh(cip)$norm."]
set l(4) [format "%-74s" "Today is $date(day) $date(date), $date(month) $date(year). The current time is $date(time) (UTC)."]
set l(5) [format "%-74s" "In case of question, issue, problem or disagreement with the rules, please"]
set l(6) [format "%-104s" "contact$pink Antoine Van Serveyt$norm by email at$pink avanserv@brinkflew.com$norm."]

puts ""
puts "$grey   $hv╔$tb╗"
puts "$grey  ╔$hb╣ $title ╠$hb╗"
puts "$grey  ║$hv╚$tb╝$hv║"
puts "$grey  ║$norm $l(1) $grey║"
puts "$grey  ║$norm $l(2) $grey║"
puts "$grey  ║                                                                            ║"
#puts "$grey  ║$norm $l(3) $grey║"
puts "$grey  ║$norm $l(4) $grey║"
puts "$grey  ║$norm $l(5) $grey║"
puts "$grey  ║$norm $l(6) $grey║"
puts "$grey  ╚════════════════════════════════════════════════════════════════════════════╝"
