#!/usr/bin/env tclsh

# Shell colors
set norm  "\033\[0m"
set grey  "\033\[38;5;238m"
set white "\033\[38;5;255m"
set pink  "\033\[38;5;162m"
set bold  "\033\[1m"

# Title
set server_rules_ "$bold$pink Server Rules $norm$grey"

puts "$grey                                 ╔══════════════╗"
puts "$grey  ╔══════════════════════════════╣$server_rules_╠══════════════════════════════╗"
puts "$grey  ║                              ╚══════════════╝                              ║"
puts "$grey  ║$norm   This is a private system that you are not to give out access to anyone   $grey║"
puts "$grey  ║$norm    without permission from the admin. Do not store any illegal file nor    $grey║"
puts "$grey  ║$norm      perform any illegal activity.  Stay in your home directory, keep      $grey║"
puts "$grey  ║$norm                 the system clean and make regular backups.                 $grey║"
puts "$grey  ║                                                                            ║"
puts "$grey  ║$norm$bold            DO NOT KEEP SENSITIVE LOGS OR HISTORY ON THIS SERVER            $norm$grey║"
puts "$grey  ╚════════════════════════════════════════════════════════════════════════════╝$norm"
puts ""
