#!/usr/bin/env tclsh

# Shell colors
set norm  "\033\[0m"
set grey  "\033\[38;5;238m"

# Draw the logo
set b "$norm█$grey"

puts ""
puts "$grey      $b$b$b$b$b$b╗ $b$b$b$b$b$b╗ $b$b╗$b$b$b╗   $b$b╗$b$b╗  $b$b╗$b$b$b$b$b$b$b╗$b$b╗     $b$b$b$b$b$b$b╗$b$b╗    $b$b╗$norm"
puts "$grey      $b$b╔══$b$b╗$b$b╔══$b$b╗$b$b║$b$b$b$b╗  $b$b║$b$b║ $b$b╔╝$b$b╔════╝$b$b║     $b$b╔════╝$b$b║    $b$b║$norm"
puts "$grey      $b$b$b$b$b$b╔╝$b$b$b$b$b$b╔╝$b$b║$b$b╔$b$b╗ $b$b║$b$b$b$b$b╔╝ $b$b$b$b$b╗  $b$b║     $b$b$b$b$b╗  $b$b║ $b╗ $b$b║$norm"
puts "$grey      $b$b╔══$b$b╗$b$b╔══$b$b╗$b$b║$b$b║╚$b$b╗$b$b║$b$b╔═$b$b╗ $b$b╔══╝  $b$b║     $b$b╔══╝  $b$b║$b$b$b╗$b$b║$norm"
puts "$grey      $b$b$b$b$b$b╔╝$b$b║  $b$b║$b$b║$b$b║ ╚$b$b$b$b║$b$b║  $b$b╗$b$b║     $b$b$b$b$b$b$b╗$b$b$b$b$b$b$b╗╚$b$b$b╔$b$b$b╔╝$norm"
puts "$grey      ╚═════╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝     ╚══════╝╚══════╝ ╚══╝╚══╝ $norm"
